### PR TITLE
Use opam-repository to determine available versions

### PR DESCRIPTION
**Pull request by schutm**
In stead of looking at the ocaml-releases I changed the list-all to look at the ocaml releases available in opam. This results for the moment in more releases available, and should help to make sure only ' 'opam-available' ocaml releases are shown.

### CODE REVIEW

**Comment by schutm** [comment]
Not sure how to create a merge-request per certain commit points. Sorry about that.

**Comment by smorimoto** [comment]
@schutm What is the current status of this PR? If it's ready for review, I will review it as soon as possible.

**Comment by smorimoto** [comment]
Rebased

**Comment by smorimoto** [comment]
This PR contains some unrelated changes, so I will update it. If you want to make other changes, please open another PR. Thanks.

**Review by smorimoto — APPROVED** [review]

**Comment by schutm** [comment]
Sorry I'm on a holiday. As said I messed the merge request a bit up (not  
familiar with git and github). I see you already merged some requests in.  
Do you want me to clean up some more?


On Fri, 23 Aug 2019 01:10:37 +0200, BSKY <notifications@github.com> wrote:

>
> @schutm What is the current status of this PR? If it's ready for review,  
> I will review it as soon as possible.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



--

**Comment by smorimoto** [comment]
@schutm No worries! I was going to make these change at some point, so this PR was good.

> Do you want me to clean up some more?

Yes, it would be great if you have much time!

**Pull request merged**
