### PR TITLE
Add support for macOS and OpenBSD

### PR DESCRIPTION
**Pull request by smorimoto**
I'm not familiar with Bash. But it should work on macOS and OpenBSD. (Tested it on macOS 10.14.5)
Would appreciate some advice if this code style is not good!

### CODE REVIEW

**Comment by smorimoto** [comment]
Maybe this pull request is related to #3.

**Comment by smorimoto** [comment]
@vic friendly ping~

**Comment by vic** [comment]
@imbsky  added you as collaborator, please merge at your discretion.

**Comment by smorimoto** [comment]
@vic Thanks Victor. I tested it locally, and it worked on Ubuntu, OpenBSD, and macOS, so I will merge it.

**Pull request merged**
